In [2]:
import pandas as pd
import numpy as np

In [5]:
# อ่านข้อมูล
play_tennis = pd.read_csv("play_tennis.csv")

In [7]:
# encode temp and play columns.
# Converting string labels into numbers

# Import LabelEncoder
from sklearn import preprocessing

#creating labelEncoder
number = preprocessing.LabelEncoder()

play_tennis['outlook'] = number.fit_transform(play_tennis['outlook'])
play_tennis['temperature'] = number.fit_transform(play_tennis['temperature'])
play_tennis['humidity'] = number.fit_transform(play_tennis['humidity'])
play_tennis['windy'] = number.fit_transform(play_tennis['windy'])

print(play_tennis)

    outlook  temperature  humidity  windy play
0         2            1         0      1   no
1         2            1         0      0   no
2         0            1         0      1  yes
3         1            2         0      1  yes
4         1            0         1      1  yes
5         1            0         1      0   no
6         0            0         1      0  yes
7         2            2         0      1   no
8         2            0         1      1  yes
9         1            2         1      1  yes
10        2            2         1      0  yes
11        0            2         0      0  yes
12        0            1         1      1  yes
13        1            2         0      0   no


sklearn library, which can be found in sklearn.naive_bayes:

sklearn.naive_bayes.CategoricalNB: 
    for using Naive Bayes on categorical predictor variables.
            
sklearn.naive_bayes.GaussianNB: 
    for Naive Bayes on numerical predictor variables, with the assumption 
    that these variables follow Gaussian distribution.
    
sklearn.naive_bayes.MultinomialNB: 
    the predictor variables represent the counts, a popular application 
    is in text classification. Fractional counts like tf-idf may also work.
    
sklearn.naive_bayes.ComplementNB: 
    A modification of MultinomialNB which is suitable for imbalanced datasets.
    
sklearn.naive_bayes.BernoulliNB: 
    assumes the data follows Bernoulli distribution (i.e. possible values of 
    predictor variables are 0 and 1).

In [8]:
#Import Library of Naive Bayes
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB, CategoricalNB

#Create a Gaussian Classifier
Cat_NB_model = CategoricalNB()

# Train the model using the training sets
Cat_NB_model.fit(play_tennis[['outlook','temperature', 'humidity','windy']],play_tennis['play'])

#Predict Output
predicted= Cat_NB_model.predict([[1,1,0,1]]) # 1:rain, 1:hot, 0:high, 1:weak
print("Predicted Value:", predicted)

Predicted Value: ['no']


C:\Users\Guest-Student\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


In [9]:
#Import Library of K-Nearest Neighbor model
from sklearn.neighbors import KNeighborsClassifier

In [12]:
#Create a KNN Classifier
knn = KNeighborsClassifier(n_neighbors=3)

# Train the model using the training sets
knn.fit(play_tennis[['outlook','temperature', 'humidity','windy']],play_tennis['play'])

#Predict Output
predicted= knn.predict([[1,1,0,1]]) 
print("Predicted Value:", predicted)

Predicted Value: ['yes']


C:\Users\Guest-Student\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


# แบบฝึกหัด

1. จากตัวอย่างข้างต้น ให้นักศึกษาทดลองใช้ GaussianNB, BernoulliNB, MultinomialNB  
เพื่อ predict ข้อมูลใหม่ที่เป็น rain, hot, high, weak ว่าเมื่อใช้แต่ละ model ได้คำตอบเป็นอะไร

In [13]:
Ga_NB_model = GaussianNB()

Ga_NB_model.fit(play_tennis[['outlook','temperature', 'humidity','windy']],play_tennis['play'])

predicted= Ga_NB_model.predict([[1,1,0,1]]) # 1:rain, 1:hot, 0:high, 1:weak
print("Predicted Value:", predicted)

Predicted Value: ['yes']


C:\Users\Guest-Student\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [14]:
Ber_NB_model = BernoulliNB()

Ber_NB_model.fit(play_tennis[['outlook','temperature', 'humidity','windy']],play_tennis['play'])

predicted= Ber_NB_model.predict([[1,1,0,1]]) # 1:rain, 1:hot, 0:high, 1:weak
print("Predicted Value:", predicted)

Predicted Value: ['no']


C:\Users\Guest-Student\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(


In [15]:
Mul_NB_model = MultinomialNB()

Mul_NB_model.fit(play_tennis[['outlook','temperature', 'humidity','windy']],play_tennis['play'])

predicted= Mul_NB_model.predict([[1,1,0,1]]) # 1:rain, 1:hot, 0:high, 1:weak
print("Predicted Value:", predicted)

Predicted Value: ['yes']


C:\Users\Guest-Student\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


2. มีข้อมูลใหม่ 2 ชุดคือ 
outlook -> Rainy, Sunny
temperature -> Cool, Mild
humidity -> high, normal
windy -> Weak, Strong

ให้ักศึกษาใช้ NB และ KNN (เมื่อ K=5) predict ข้อมูลใหม่ว่าอยู่ใน class อะไร

In [39]:
# สร้าง dataframe ชื่อ person ว่างๆ ขึ้นมาก่อน
person = pd.DataFrame()

# สร้างข้อมูลที่เป็น new data มี 2 คน
person['outlook'] = ['Rainy', 'Sunny']
person['temperature'] = ['Cool', 'Mild']
person['humidity'] = ['high', 'normal']
person['windy'] = ['Weak', 'Strong']

# View the data 
person

outlook temperature humidity   windy
0   Rainy        Cool     high    Weak
1   Sunny        Mild   normal  Strong

In [40]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
outlook_encoded=le.fit_transform(play_tennis['outlook'])
temperature_encoded=le.fit_transform(play_tennis['temperature'])
humidity_encoded=le.fit_transform(play_tennis['humidity'])
windy_encoded=le.fit_transform(play_tennis['windy'])

print(outlook_encoded)
print(temperature_encoded)
print(humidity_encoded)
print(windy_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 0 0 1 1 1 0 1 1 1 0 1 0]
[1 0 1 1 1 0 0 1 1 1 0 0 1 0]


In [41]:
#Combinig weather and temp into single listof tuples
features=list(zip(outlook_encoded,temperature_encoded,humidity_encoded,windy_encoded))
print(features)

[(2, 1, 0, 1), (2, 1, 0, 0), (0, 1, 0, 1), (1, 2, 0, 1), (1, 0, 1, 1), (1, 0, 1, 0), (0, 0, 1, 0), (2, 2, 0, 1), (2, 0, 1, 1), (1, 2, 1, 1), (2, 2, 1, 0), (0, 2, 0, 0), (0, 1, 1, 1), (1, 2, 0, 0)]


In [48]:
Ga_NB_model = GaussianNB()

Ga_NB_model.fit(features,play_tennis['play'])

predicted= Ga_NB_model.predict([[1,0,0,1],[2,2,1,0]])
print("Predicted Value:", predicted)

Predicted Value: ['yes' 'yes']


In [49]:
#Create a KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5)

# Train the model using the training sets
knn.fit(features,play_tennis['play'])

#Predict Output
predicted= knn.predict([[1,0,0,1],[2,2,1,0]])
print("Predicted Value:", predicted)

Predicted Value: ['yes' 'no']
